# Generated by Django 4.2 on 2023-05-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartapp', '0004_alter_valuestore_oldpeak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuestore',
            name='oldpeak',
            field=models.FloatField(),
        ),
    ]
